sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
env:
  - SYMFONY="2.7.*"
  - SYMFONY="~3.0"
services:
  - elasticsearch
install:
  - composer require --no-update symfony/symfony:${SYMFONY}
  - wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-2.3.3.tar.gz
  - tar -xzf elasticsearch-2.3.3.tar.gz
  - ./elasticsearch-2.3.3/bin/elasticsearch > /dev/null 2>&1 &
before_script:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover=coveralls.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/,Resources/public/ ./
after_script:
  - vendor/bin/coveralls